[platformio]
src_dir = .

[env:esp32s3]
platform = espressif32
board = esp32s3_120_16_8-qio_opi
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM6
build_src_filter =
  +<*.ino>
  +<*.cpp>
lib_deps =
  adafruit/Adafruit GFX Library
  solderedelectronics/Soldered PCF85063A RTC Library
  tzapu/WiFiManager
  bblanchon/ArduinoJson
  bodmer/TJpg_Decoder
  earlephilhower/ESP8266Audio
  knolleary/PubSubClient
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=0

